// Code generated by mockery v1.0.0. DO NOT EDIT.

package repeater

import mock "github.com/stretchr/testify/mock"

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

// Add provides a mock function with given fields: r
func (_m *MockStore) Add(r Rule) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(Rule) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockStore) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: req
func (_m *MockStore) Find(req FindReq) ([]Rule, error) {
	ret := _m.Called(req)

	var r0 []Rule
	if rf, ok := ret.Get(0).(func(FindReq) []Rule); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Rule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(FindReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
