run:
  tests: false
  output:
    format: tab
  skip-dirs:
    - vendor

linters:
  enable:
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - golint
  disable-all: true

issues:
  exclude-use-default: false