version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: semior/multibot:latest
    container_name: "multibot"
    hostname: "multibot"
    volumes:
      - ./db:/db/ # add your database location here
    environment:
      DEBUG: 'true'
      TOKEN: ''
      USERNAME: ''
      LOCATION: '/db/botdb.db'
    ports:
      - 8080:8080
    command: ["/entrypoint.sh", "telegram"]
